import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import { CartProvider } from "../context/CartContext";
// 🔮 Next.js এর অফিসিয়াল Script কম্পোনেন্ট ইম্পোর্ট করা হলো
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZYRA",
  description: "Generated by ZYRA",
  icons: {
    icon: '/zyra.webp',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased suppressHydrationWarning`}
      >
        <CartProvider>
          {children}
        </CartProvider>

        {/* 💳 Razorpay SDK - Next.js স্ট্যান্ডার্ড অনুযায়ী বডির ভেতরে লোড করা হলো */}
        <Script 
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload" // পেজ লোড হওয়ার পর ব্যাকগ্রাউন্ডে স্ক্রিপ্টটি লোড হবে, ফলে সাইট থাকবে সুপার ফাস্ট
        />
      </body>
    </html>
  );
}